import { Welcome } from "@monorepo/hello-ui";
import Head from "next/head";
export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Welcome />
    </>
  );
}
